version: "3.8"

services:
  handler:
    build: ../handler/Dockerfile
    container_name: handler
    hostname: handler
    volumes:
      - ./:/app
      - /usr/local/lib/python3.12/site-packages
  concierge:
    build: ../concierge/Dockerfile
    container_name: concierge
    hostname: concierge
    volumes:
      - ./:/app
      - /usr/local/lib/python3.12/site-packages
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    hostname: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb:/home/dynamodblocal  # Mount the local directory to the container
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    hostname: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
