version: "3.8"

services:
  handler:
    build:
      context: ./
      dockerfile: handler/Dockerfile
    container_name: handler
    hostname: handler
    env_file:
      - config/handler.env
    volumes:
      - handler-store:/handler
    ports:
      - "8008:8008"

  concierge:
    build:
      context: ./
      dockerfile: concierge/Dockerfile
    container_name: concierge
    hostname: concierge
    env_file:
      - config/concierge.env
    volumes:
      - concierge-store:/concierge
    ports:
      - "8088:8088"

  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    hostname: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - db-store:/home/dynamodblocal/data  # Mount the local directory to the container
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    hostname: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000

volumes:
     db-store:
       driver: local
     handler-store:
       driver: local
     concierge-store:
       driver: local
